### ISSUE TITLE
Cannot install on Node 0.8.x because npm doesn't understand ^1.0.0

### ISSUE THREAD

**Issue by jameshartig** [tapjs/tapjs#115]
Trying to install tap 0.6.0 in Node 0.8.x doesn't work since the new dependencies require `deep-equal@'^1.0.0'` which apparently that version of npm doesn't understand?

```
npm ERR! Error: No compatible version found: deep-equal@'^1.0.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.0","0.1.0","0.1.1","0.1.2","0.2.0","0.2.1","0.2.2","1.0.0"]
npm ERR!     at installTargetsError (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

Example build: https://travis-ci.org/fastest963/ChainLoading/jobs/50595075

Thanks!

**Comment by maraca** [comment]
+1

**Comment by isaacs** [comment]
Use a more recent version of npm. `npm i -g npm`
