### ISSUE TITLE
Unhandled rejection when using markdown reporter

### ISSUE THREAD

**Issue by tjconcept** [tapjs/tapjs#146]
``` shell
~/project (master) $ npm test | tap -R markdown -
/home/tj/.npm-conf/lib/node_modules/tap/node_modules/tap-mocha-reporter/lib/reporters/markdown.js:45
        key = SUITE_PREFIX + suite.title;
                                  ^
TypeError: Cannot read property 'title' of undefined
    at mapTOC (/home/tj/.npm-conf/lib/node_modules/tap/node_modules/tap-mocha-reporter/lib/reporters/markdown.js:45:35)
    at generateTOC (/home/tj/.npm-conf/lib/node_modules/tap/node_modules/tap-mocha-reporter/lib/reporters/markdown.js:70:15)
    at new Markdown (/home/tj/.npm-conf/lib/node_modules/tap/node_modules/tap-mocha-reporter/lib/reporters/markdown.js:74:3)
    at new Formatter (/home/tj/.npm-conf/lib/node_modules/tap/node_modules/tap-mocha-reporter/index.js:48:19)
    at Object.<anonymous> (/home/tj/.npm-conf/lib/node_modules/tap/bin/run.js:340:14)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Function.Module.runMain (module.js:467:10)
```

**Comment by isaacs** [comment]
Technically this is an issue with https://github.com/isaacs/tap-mocha-reporter

It needs a suite to exist and have a title before we have a suite yet.

**Comment by tjconcept** [comment]
Okay. Just wanted to report it :)
