### ISSUE TITLE
Somewhat unintuitive yaml block when expecting undefined

### ISSUE THREAD

**Issue by evanlucas** [tapjs/tapjs#327]
```
$ npm ls tap
/Users/evan/dev/code/testcases
└── tap@7.1.2 

$ uname -a
Darwin iMac.local 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64
```

If you run `node -pe "require('tap').equal(null, undefined)"`, it prints the following:

``` yaml
TAP version 13
not ok 1 - should be equal
  ---
  found: null
  wanted: null # <------- This should show undefined?
  compare: ===
  at:
    line: 1
    column: 16
    file: '[eval]'
  stack: |
    [eval]:1:16
    ContextifyScript.Script.runInThisContext (vm.js:25:33)
    Object.exports.runInThisContext (vm.js:77:17)
    Object.<anonymous> ([eval]-wrapper:6:22)
    bootstrap_node.js:357:29
    _combinedTickCallback (internal/process/next_tick.js:67:7)
    process._tickCallback (internal/process/next_tick.js:98:9)
  ...
false
1..1
# failed 1 of 1 tests
# time=17.021ms
```

**Comment by isaacs** [comment]
Sorry, yaml does not have `undefined`.

```
> require('js-yaml').safeDump({foo:undefined})
YAMLException: unacceptable kind of an object to dump [object Undefined]
    at writeNode (/Users/isaacs/dev/js/tap/node_modules/js-yaml/lib/js-yaml/dumper.js:731:13)
    at writeBlockMapping (/Users/isaacs/dev/js/tap/node_modules/js-yaml/lib/js-yaml/dumper.js:610:10)
    at writeNode (/Users/isaacs/dev/js/tap/node_modules/js-yaml/lib/js-yaml/dumper.js:703:9)
    at dump (/Users/isaacs/dev/js/tap/node_modules/js-yaml/lib/js-yaml/dumper.js:792:7)
    at Object.safeDump (/Users/isaacs/dev/js/tap/node_modules/js-yaml/lib/js-yaml/dumper.js:798:10)
    at repl:1:20
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
```

**Comment by evanlucas** [comment]
ah, that makes more sense. Thanks for the clarification @isaacs!
