### ISSUE TITLE
Tests throw when coverage is enabled but there are no tests

### ISSUE THREAD

**Issue by toddself** [tapjs/tapjs#328]
Kind of an odd one, since like why would you run tests if there are none, but I would expect this to succeed since nothing was failing.  Not sure if tap should be doing a try/catch here for the NYC command, or if this should go into NYC?

Simple repo:

``` bash
> mkdir /tmp/tap-test
> cd /tmp/tap-test
> npm init -y
> npm i tap
> node_modules/.bin/tap --cov --coverage-report lcov *.js
```

```
↳ node_modules/.bin/tap --cov --coverage-report lcov  *.spec.js
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/private/tmp/tap-test/.nyc_output'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at NYC._loadReports (/private/tmp/tap-test/node_modules/nyc/index.js:438:18)
    at NYC.report (/private/tmp/tap-test/node_modules/nyc/index.js:401:8)
    at report (/private/tmp/tap-test/node_modules/nyc/bin/nyc.js:107:7)
    at Object.<anonymous> (/private/tmp/tap-test/node_modules/nyc/bin/nyc.js:23:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

**Comment by isaacs** [comment]
No longer an issue.
