### ISSUE TITLE
Failed to run tap in Electron (renderer process).

### ISSUE THREAD

**Issue by jwu** [tapjs/tapjs#347]
Hi, 

I try to run tap in the renderer process of Electron. Things go well, until I use timeout option. It finally throw an issue relate to this line of code:

https://github.com/tapjs/node-tap/blob/master/lib/base.js#L76

Here is my error stack:

```javascript
TypeError: this.timer.unref is not a function
    at Test.Base.setTimeout (/Users/johnny/electron-utils/electron-tap/node_modules/tap/lib/base.js:76:16)
    at Test.main (/Users/johnny/electron-utils/electron-tap/node_modules/tap/lib/test.js:181:8)
    at TAP.Test.writeSubComment (/Users/johnny/electron-utils/electron-tap/node_modules/tap/lib/test.js:311:3)
    at loop (/Users/johnny/electron-utils/electron-tap/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/Users/johnny/electron-utils/electron-tap/node_modules/tap/lib/test.js:633:5)
    at TAP.Test.processSubtest (/Users/johnny/electron-utils/electron-tap/node_modules/tap/lib/test.js:285:10)
    at TAP.Test.process (/Users/johnny/electron-utils/electron-tap/node_modules/tap/lib/test.js:229:12)
    at TAP.Test.sub (/Users/johnny/electron-utils/electron-tap/node_modules/tap/lib/test.js:132:8)
    at TAP.test (/Users/johnny/electron-utils/electron-tap/node_modules/tap/lib/test.js:138:15)
    at tap.suite (/Users/johnny/electron-utils/electron-tap/lib/share/tap.js:72:12)
    at Object.<anonymous> (/Users/johnny/electron-utils/electron-tap/test/renderer/helper.spec.js:3:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

This is because in Electron's renderer process (or Web Browser), setTimeout will return a number instead of a timer object. So there is no unref in it.

I think this can be fixed by check `this.timer`. It will be awesome that `node-tap` can support more platform.

**Comment by isaacs** [comment]
Should be fixed in 10.1 release.
