### ISSUE TITLE
Error message is swallowed. Object.keys does not work for enumerable:false properties

### ISSUE THREAD

**Issue by dotnetCarpenter** [tapjs/tapjs#366]
I'm using `doesNotThrow()` and are getting a `TypeError` but I can not see it in the output.

I tracked it down to `extra-from-error.js`, line 36 - using node-tap 10.3.2.

```js
Object.keys(er).forEach(function (k) {
    if (k === 'message' ||
        k === 'domainEmitter' ||
        k === 'domainThrown' ||
        k === 'domain' ||
        k === 'domainBound')
      return
    extra[k] = er[k]
  })

  return extra
```

The problem is that `Object.keys(er)` returns an array with length 0. 

`Object.getOwnPropertyDescriptors(er)`:
```
configurable:true
enumerable:false
value:"First argument must be file descriptor"
writable:true
__proto__:Object {__defineGetter__: function __defineGetter__() { [native code] }, __defineSetter__: function __defineSetter__() { [native code] }, hasOwnProperty: function hasOwnProperty() { [native code] } …}
stack:Object {value: "TypeError: First argument must be file descriptor\n…", writable: true, enumerable: false …}
__proto__:Object {__defineGetter__: function __defineGetter__() { [native code] }, __defineSetter__: function __defineSetter__() { [native code] }, hasOwnProperty: function hasOwnProperty() { [native code] } …}
```

The arguments to `module.exports = function (er, extra, options) {` are:

```
er: {
message: "First argument must be file descriptor",
stack: "TypeError: First argument must be file descriptor
    at fs.write (fs.js:730:18)
    at through (/home/dotnet/projects/opensource/gulp-tap/src/tap.coffee:32:23)
    at Test.<anonymous> (/home/dotnet/projects/opensource/gulp-tap/node_modules/tap/lib/asserts.js:265:7)
    at Test.ASSERT [as currentAssert] (/home/dotnet/projects/opensource/gulp-tap/node_modules/tap/lib/test.js:414:15)
    at /home/dotnet/projects/opensource/gulp-tap/tests/throws.test.coffee:38:9
    at DestroyableTransform.modifyFile (/home/dotnet/projects/opensource/gulp-tap/src/tap.coffee:44:11)
    at DestroyableTransform.Transform._read (/home/dotnet/projects/opensource/gulp-tap/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/dotnet/projects/opensource/gulp-tap/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/dotnet/projects/opensource/gulp-tap/node_modules/readable-stream/lib/_stream_writable.js:345:64)
    at writeOrBuffer (/home/dotnet/projects/opensource/gulp-tap/node_modules/readable-stream/lib/_stream_writable.js:334:5)
    at DestroyableTransform.Writable.write (/home/dotnet/projects/opensource/gulp-tap/node_modules/readable-stream/lib/_stream_writable.js:271:11)
    at write (/home/dotnet/projects/opensource/gulp-tap/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/dotnet/projects/opensource/gulp-tap/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/home/dotnet/projects/opensource/gulp-tap/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:188:7)",
  __proto__: TypeError {name: "TypeError", message: "", constructor: function TypeError() { [native code] } …}
},
extra: Object,
options: undefined
```

PS:
Not sure why the error message is removed and then added again to the error object.

```js
er.message = '' // message is removed
var st = er.stack
if (st) {
  st = st.split('\n')
  // parse out the 'at' bit from the first line.
  extra.at = stack.parseLine(st[1])
  extra.stack = stack.clean(st)
}
er.message = message // message is added again
```
_Are you trying to make it enumerable?_

**Comment by isaacs** [comment]
The point of that bit of code is to get a stack that doesn't include the message.  It's not safe to split on `\n`, since the message can contain line breaks.

I'd think that putting the message back would fix the problem.  The issue with the change in #367 is that you end up with a message that's repeated in the extra object.  So it's like doing `t.fail('foo', { message: 'foo' })` which is a bit redundant.

For example:

```
$ node -e 'require("./").threw(new Error("foo"))'
TAP version 13
not ok 1 - foo
  ---
  stack: |
    [eval]:1:-41
    Object.<anonymous> ([eval]-wrapper:6:22)
  test: TAP
  message: foo
  ...

1..1
# failed 1 test
# time=13.277ms
```

It's only showing in the teardown-throw message test because the other tests are doing a `t.match`, so extra fields are ignored.  But if you run `npm run regen-fixtures`, you'll see that this patch changes quite a lot of test output.

I'll land a more surgical fix to #366 shortly.
