### ISSUE TITLE
Code coverage with @std/esm, nyc, and tap

### ISSUE THREAD

**Issue by davidbonnet** [tapjs/tapjs#400]
Sorry for cross-posting, but I am trying to get coverage for ES modules using `@std/esm` and I am having a hard time figuring out why:

```bash
tap --node-arg=--require --node-arg=@std/esm tests.js
```

…works but:

```bash
tap --node-arg=--require --node-arg=@std/esm --nyc-arg=--require --nyc-arg=@std/esm --coverage tests.js
```

…doesn't.

Testing repository: https://github.com/davidbonnet/tests
Related issue: https://github.com/standard-things/esm/issues/83

**Comment by jdalton** [comment]
@davidbonnet You might try again with an updated version of `@std/esm`.

**Comment by stefanmaric** [comment]
> @davidbonnet You might try again with an updated version of @std/esm.

@jdalton I got the very same problem today with `esm@3.0.24` and found this thread.

I've been trying to debug for a while with little success. But the problem seems to be more on `nyc`'s side and unrelated to tap.

Given this small setup:

```shell
npm init -y
npm install --save-dev nyc esm
echo 'export default "a"' >> a.mjs
echo 'import a from "./a"' >> b.mjs
echo 'export default `${a} imported by b`' >> b.mjs
echo 'import b from "./b"' >> c.mjs
echo 'console.log(`${b} imported from c`)' >> c.mjs
```

Running `node -r esm c.mjs` runs as expected.

Instead, running:

```shell
./node_modules/.bin/nyc -i esm -e .mjs -- node -r esm c.mjs
```

Breaks with:

```
/home/sam/Code/stefanmaric/nyc-test/c.mjs:1
var sw = require('spawn-wrap')

(function (exports, require, module, __filename, __dirname) { var cov_2irgm4wk7k=function(){var path="/home/sam/Code/stefanmaric/nyc-test/c.mjs",hash="df9295c5340b52ad5d3c2c444ad0d55b27726d9a",Function=function(){}.constructor,global=new Function('return this')(),gcv="__coverage__",coverageData={path:"/home/sam/Code/stefanmaric/nyc-test/c.mjs",statementMap:{"0":{start:{line:2,column:0},end:{line:2,column:35}}},fnMap:{},branchMap:{},s:{"0":0},f:{},b:{},_coverageSchema:"332fd63041d2c1bcb487cc26dd0d5f7d97098a6c"},coverage=global[gcv]||(global[gcv]={});if(coverage[path]&&coverage[path].hash===hash){return coverage[path];}coverageData.hash=hash;return coverage[path]=coverageData;}();import b from"./b";cov_2irgm4wk7k.s[0]++;console.log(`${b} imported from c`);
                                                                                                                                                                                                                     

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at runInThisContext (vm.js:197:10)
    at Object.vm.runInThisContext (/home/sam/Code/stefanmaric/nyc-test/node_modules/nyc/node_modules/istanbul-lib-hook/lib/hook.js:142:16)
    at Module._compile (module.js:613:28)
    at Module.replacementCompile (/home/sam/Code/stefanmaric/nyc-test/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/home/sam/Code/stefanmaric/nyc-test/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/home/sam/Code/stefanmaric/nyc-test/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|

```

By simply removing the `-e` param from nyc it works but no code is covered; what makes me think it is indeed `nyc` trying to instrument what breaks it.

And trying to running `nyc` with `node -r esm` has no difference.

More about the env I'm testing on:

```shell
$ uname -a
Linux sam-xps-ubuntu 4.15.18-041518-generic #201804190330 SMP Thu Apr 19 07:34:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ node -v
v9.10.1
$ npm -v
5.6.0
$ npm ls --depth=0
nyc-test@1.0.0 /home/sam/Code/stefanmaric/nyc-test
├── esm@3.0.24
└── nyc@11.7.1
```

**Comment by jdalton** [comment]
Hi @stefanmaric!

This works
```shell
npx nyc -i esm -e .mjs node ./c.mjs
```
or
```shell
npx nyc -i esm -e .mjs -- node ./c.mjs
```

**Comment by stefanmaric** [comment]
> This works

Alright, that surprised me.

So why does requiring esm twice breaks it? The same apply for `tap`+`nyc`, under the same test setup as before, these two commands work:

```
./node_modules/.bin/tap --node-arg=-r --node-arg=esm c.mjs
```

```
./node_modules/.bin/tap --cov --nyc-arg=-i --nyc-arg=esm --nyc-arg=-e --nyc-arg=.mjs c.mjs
```

Notes there:
* Added `tap` to the setup (`npm install --save-dev tap`).
* I'm executing  the files directly instead of using `npx` just to remove it from the equation since I don't understand its internals.
* For tap to actually work with .mjs files, had to edit [this regex](https://github.com/tapjs/node-tap/blob/8635bfb083da8f29a8f54f4bef331a01e5ad6b1a/bin/run.js#L731).

But mixing the two commands breaks:

```
./node_modules/.bin/tap --node-arg=-r --node-arg=esm --cov --nyc-arg=-i --nyc-arg=esm --nyc-arg=-e --nyc-arg=.mjs c.mjs
```

```
/home/sam/Code/stefanmaric/nyc-test/c.mjs:1
var sw = require('spawn-wrap')

(function (exports, require, module, __filename, __dirname) { var cov_2irgm4wk7k=function(){var path="/home/sam/Code/stefanmaric/nyc-test/c.mjs",hash="df9295c5340b52ad5d3c2c444ad0d55b27726d9a",Function=function(){}.constructor,global=new Function('return this')(),gcv="__coverage__",coverageData={path:"/home/sam/Code/stefanmaric/nyc-test/c.mjs",statementMap:{"0":{start:{line:2,column:0},end:{line:2,column:35}}},fnMap:{},branchMap:{},s:{"0":0},f:{},b:{},_coverageSchema:"332fd63041d2c1bcb487cc26dd0d5f7d97098a6c"},coverage=global[gcv]||(global[gcv]={});if(coverage[path]&&coverage[path].hash===hash){return coverage[path];}coverageData.hash=hash;return coverage[path]=coverageData;}();import b from"./b";cov_2irgm4wk7k.s[0]++;console.log(`${b} imported from c`);
                                                                                                                                                                                                                     

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at runInThisContext (vm.js:197:10)
    at Object.vm.runInThisContext (/home/sam/Code/stefanmaric/nyc-test/node_modules/nyc/node_modules/istanbul-lib-hook/lib/hook.js:142:16)
    at Module._compile (module.js:613:28)
    at Module.replacementCompile (/home/sam/Code/stefanmaric/nyc-test/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/home/sam/Code/stefanmaric/nyc-test/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/home/sam/Code/stefanmaric/nyc-test/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
c.mjs ................................................. 0/1
  not ok c.mjs
    timeout: 240000
    file: c.mjs
    command: /home/sam/n/bin/node
    args:
      - '-r'
      - esm
      - c.mjs
    stdio:
      - 0
      - pipe
      - 2
    cwd: /home/sam/Code/stefanmaric/nyc-test
    exitCode: 1

total ................................................. 0/1
  

  0 passing (438.062ms)
  1 failing

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
```

Inspecting the code, I can trace the following spawn chain for each variant:

Good:

```
./node_modules/.bin/tap --node-arg=-r --node-arg=esm c.mjs

/home/sam/n/bin/node [ '-r', 'esm', 'c.mjs' ]
```

Good:

```
./node_modules/.bin/tap --cov --nyc-arg=-i --nyc-arg=esm --nyc-arg=-e --nyc-arg=.mjs c.mjs
/home/sam/n/bin/node [
  '/home/sam/Code/stefanmaric/nyc-test/node_modules/nyc/bin/nyc.js',
  '--silent',
  '--cache=true',
  '-i',
  'esm',
  '-e',
  '.mjs',
  '--',
  '/home/sam/Code/stefanmaric/nyc-test/node_modules/.bin/tap',
  '--cov',
  '--nyc-arg=-i',
  '--nyc-arg=esm',
  '--nyc-arg=-e',
  '--nyc-arg=.mjs',
  'c.mjs'
]

/home/sam/n/bin/node [ 'c.mjs' ]
```

Bad:

```
./node_modules/.bin/tap --node-arg=-r --node-arg=esm --cov --nyc-arg=-i --nyc-arg=esm --nyc-arg=-e --nyc-arg=.mjs c.mjs

/home/sam/n/bin/node [
  '/home/sam/Code/stefanmaric/nyc-test/node_modules/nyc/bin/nyc.js',
  '--silent',
  '--cache=true',
  '-i',
  'esm',
  '-e',
  '.mjs',
  '--',
  '/home/sam/Code/stefanmaric/nyc-test/node_modules/.bin/tap',
  '--node-arg=-r',
  '--node-arg=esm',
  '--cov',
  '--nyc-arg=-i',
  '--nyc-arg=esm',
  '--nyc-arg=-e',
  '--nyc-arg=.mjs',
  'c.mjs'
]

/home/sam/n/bin/node [ '-r', 'esm', 'c.mjs' ]
```

So by avoiding spawning node with `-r esm`, as on your example, prevents it from breaking, but why?

**Comment by jdalton** [comment]
> So by avoiding spawning node with `-r esm`, as on your example, prevents it from breaking, but why?

I don't know yet. But I'm gonna figure that one out and either fix it or provide a better error.

**Update:**

Following up, I filed a question https://github.com/istanbuljs/nyc/issues/824 to see what the differences between the two invocations is. On the `esm` side I've started improving the `runMain` hook to allow multiple ESM enabled invocations which I noticed `nyc` was doing. I've also ensured that `.mjs` files remain locked down. So for test coverage you'll want to switch to `.js`.

**Comment by jdalton** [comment]
Hi @stefanmaric!

Following up. I filed a question https://github.com/istanbuljs/nyc/issues/824 to see about the differences between the two invocations. On the `esm` side I've started improving the `runMain` hook to allow multiple ESM enabled invocations which I noticed nyc was doing. I've also ensured though that `.mjs` files remain locked down. So for test coverage you'll want to switch to `.js`.

**Comment by isaacs** [comment]
This is outdated, and will be made irrelevant by #503.
