### ISSUE TITLE
npm install tap returns a zlib error

### ISSUE THREAD

**Issue by tjmonsi** [tapjs/tapjs#464]
I am getting this error when I try to install `tap` on a project:

```
  npm ERR! code Z_BUF_ERROR
  npm ERR! errno -5
  npm ERR! zlib: unexpected end of file
```

The command that i am trying to do is this:
```
  npm i --save-dev tap
```

Node version is: `10.7.0`
Npm version is `6.2.0`
Running on Mac osx 

Here's the complete error
```
83 verbose stack ZlibError: zlib: unexpected end of file
83 verbose stack     at Zlib.(anonymous function).onerror (/Users/tjmonsi/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/minizlib/index.js:131:21)
83 verbose stack     at Unzip.write (/Users/tjmonsi/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/minizlib/index.js:255:31)
83 verbose stack     at Unzip.flush (/Users/tjmonsi/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/minizlib/index.js:222:10)
83 verbose stack     at Unzip.end (/Users/tjmonsi/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/minizlib/index.js:229:10)
83 verbose stack     at Object.end (/Users/tjmonsi/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:415:21)
83 verbose stack     at PassThrough.onend (_stream_readable.js:625:10)
83 verbose stack     at Object.onceWrapper (events.js:273:13)
83 verbose stack     at PassThrough.emit (events.js:187:15)
83 verbose stack     at endReadableNT (_stream_readable.js:1081:12)
83 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
```

Purpose of this project is to follow the testing tutorial in `fastify`.

**Comment by isaacs** [comment]
Not a tap error.  Looks like your npm client is getting flummoxed somehow.
