### ISSUE TITLE
nyc@13 does not support Node 4

### ISSUE THREAD

**Issue by NatalieWolfe** [tapjs/tapjs#479]
Tap lists support back to Node 4 in its `package.json` engines field. However, `nyc@13` only supports back to Node 6. This is causing issues with builds on old versions of Node:

```sh
/home/travis/build/.../node_modules/tap/node_modules/nyc/node_modules/find-up/index.js:5
module.exports = (filename, opts = {}) => {
                                 ^
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/.../node_modules/tap/node_modules/nyc/lib/config-util.js:6:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by rmg** [comment]
@isaacs it looks like you fixed this just _after_ the most recent release. Any chance of a new release soon?
