### ISSUE TITLE
.rejects() and .resolves() can throw when using --bailout

### ISSUE THREAD

**Issue by darinspivey** [tapjs/tapjs#583]
When using `.rejects()` and .`resolves()`, with the bailout flag, it throws a `TypeError` if the assertion fails.  For example, if a rejection is checking for a certain `code` and it doesn't get that code, or if something is supposed to resolve, but throws unexpectedly.  Apparently this only happens when awaiting something else within the test, such as a sleep or a database query. 

System info:
```
Tap version: 14.4.1
Node version: 10.15.0
OS: MacOS High Sierra
Command line: tap --no-coverage -Rtap -b my_test.js
```

Both of these will throw a TypeError within the tap lib:

```
'use strict'
const tap = require('tap')

const sleep = (duration) => {
  return new Promise((resolve) => {
    setTimeout(resolve, duration)
  })
}

tap.test('test', async (t) => {
  t.resolves(async () => {
    await sleep(500)
    throw new Error('This is unexpected')
  })
})
```

OR

```
tap.test('test', async (t) => {
  t.rejects(async () => {
    await sleep(500)
    const er = new Error('An error with a mis-matched code in the assertion')
    er.code = 'EINVAL'
    throw er
  }, {
    code: 'ENOPE'
  })
})
```

...both produce:

```
TAP version 13
(node:13466) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'abort' of undefined
    at Test.endAll (/Users/xxx/node_modules/tap/lib/test.js:954:18)
    at TAP.endAll (/Users/xxx/node_modules/tap/lib/test.js:952:11)
    at TAP.onbail (/Users/xxx/node_modules/tap/lib/test.js:940:12)
    at Parser.parser.once.reason (/Users/xxx/node_modules/tap/lib/base.js:278:48)
    at Object.onceWrapper (events.js:273:13)
    at Parser.emit (events.js:182:13)
    at Parser.EventEmitter.emit (domain.js:441:20)
    at Parser.emit (/Users/xxx/node_modules/tap/node_modules/minipass/index.js:307:25)
    at Parser.bailout (/Users/xxx/node_modules/tap/node_modules/tap-parser/index.js:515:10)
    at Parser.bailout (/Users/xxx/node_modules/tap/node_modules/tap-parser/index.js:518:19)
(node:13466) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13466) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ferm10n** [comment]
I ran into this bug today as well, and noticed a few things.

- This simple test file will throw a TypeError as well:
```js
import { test } from 'tap';

test(t => {
    t.resolves(new Promise((resolve, reject) => {
        setTimeout(reject);
    }));
});
```
- no other tests in the queue is needed to cause the error
- replacing `setTimeout(reject)` with `process.nextTick(reject)` will not cause the error!
- tap/lib/test.js:954 has:
```js
      if (p.endAll)
        p.endAll(true)
      else {
        p.parser.abort('test unfinished')
      }
```
and replacing it with:
```js
      if (p.endAll)
        p.endAll(true)
      else if (p.parser) {
        p.parser.abort('test unfinished')
      }
```
seems to fix it, but idk enough about the internal mechanics of tap to understand if that's a *good* fix.
- still trying to figure out how to add a unit test for this condition in the node-tap project, not sure how or where to add a snapshot

**Comment by isaacs** [comment]
You can update snapshots by adding a new test that does `t.matchSnapshot(actual, 'some nice human words content')` and then running `npm run snap`.

I've got a fix for this, though, it ended up being kind of a deep dive into some internals.
