### ISSUE TITLE
Error: Cannot find module './reports/base'

### ISSUE THREAD

**Issue by mateusvahl** [tapjs/tapjs#624]
I just installed tap and received the follow errors:

![Screen Shot 2019-12-02 at 13 04 56](https://user-images.githubusercontent.com/4995440/69975370-d8878000-1505-11ea-9150-a9b6dff513d1.png)

How to reproduce:
1. Install tap and esm: `yarn add tap esm`
```json
{
  "tap": "14.10.2",
  "esm": "^3.2.25"
}
```

2. Tap a file: `tap my-test-file.js`

```js
const tap = require('tap')
tap.pass('this is fine')
```

**Info**
- macOS with docker
- node version: 10.16.3

**How did I solved:**

It seems that adding a reporter solves the problem: `tap my-test-file.js --reporter classic`

Let me know if you need more information,
Best

**Comment by coreyfarrell** [comment]
I've experienced this issue as well with npm.  I determined that having `babel.config.js` which enables the plugin `@babel/plugin-transform-modules-commonjs` caused the issue.  This would include `@babel/preset-env`. CC @jaydenseric

Adding `ignore: ['**/node_modules/**']` to my babel.config.js worked around this issue.  I've posted a PR to import-jsx to fix this issue.

**Comment by coreyfarrell** [comment]
Not sure what happened, the `ignore: ['**/node_modules/**']` was working earlier (I think) but now it's not for me.  I've rewritten my `babel.config.js` to restrict all options within the `overrides` option:
```js
'use strict';

module.exports = {
	overrides: [{
		test: ['src/**'],
		plugins: [
			'@babel/plugin-transform-modules-commonjs'
		]
	}]
};
```

**Comment by coreyfarrell** [comment]
This issue should be resolved by tap@14.10.6, can anyone confirm?

**Comment by coreyfarrell** [comment]
If anyone still experiences the issue with tap 14.10.6+ let us know and this issue can be reopened.

**Comment by BethGriggs** [comment]
I'm seeing something similar to this with certain modules and Node.js 16. For example, this is from running npm's test suite: 

```
 added 522 packages, and changed 14 packages in 41s
 > npm@7.8.0 test
 > tap
 TAP version 13
 1..0
 # time=3.497ms
 ----------|----------|----------|----------|----------|-------------------|
 File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
 ----------|----------|----------|----------|----------|-------------------|
 All files |        0 |        0 |        0 |        0 |[31;1m                  [0m |
 ----------|----------|----------|----------|----------|-------------------|
 Error: Cannot find module './reports/base'
 Require stack:
 - /home/iojs/tmp/citgm_tmp/81754b80-27f7-459c-8dc8-8e0b3ae2f845/npm/node_modules/jackspeak/noop.js
     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
     at resolveFileName (/home/iojs/tmp/citgm_tmp/81754b80-27f7-459c-8dc8-8e0b3ae2f845/npm/node_modules/tap/node_modules/resolve-from/index.js:17:39)
     at resolveFrom (/home/iojs/tmp/citgm_tmp/81754b80-27f7-459c-8dc8-8e0b3ae2f845/npm/node_modules/tap/node_modules/resolve-from/index.js:31:9)
     at module.exports (/home/iojs/tmp/citgm_tmp/81754b80-27f7-459c-8dc8-8e0b3ae2f845/npm/node_modules/tap/node_modules/resolve-from/index.js:34:41)
     at importJSX (/home/iojs/tmp/citgm_tmp/81754b80-27f7-459c-8dc8-8e0b3ae2f845/npm/node_modules/tap/node_modules/import-jsx/index.js:24:21)
     at module.exports (/home/iojs/tmp/citgm_tmp/81754b80-27f7-459c-8dc8-8e0b3ae2f845/npm/node_modules/tap/node_modules/treport/lib/index.js:13:18)
     at exports.makeReporter (/home/iojs/tmp/citgm_tmp/81754b80-27f7-459c-8dc8-8e0b3ae2f845/npm/node_modules/tap/bin/run.js:422:23)
     at runTests (/home/iojs/tmp/citgm_tmp/81754b80-27f7-459c-8dc8-8e0b3ae2f845/npm/node_modules/tap/bin/run.js:744:3)
     at mainAsync (/home/iojs/tmp/citgm_tmp/81754b80-27f7-459c-8dc8-8e0b3ae2f845/npm/node_modules/tap/bin/run.js:244:5)
     at main (/home/iojs/tmp/citgm_tmp/81754b80-27f7-459c-8dc8-8e0b3ae2f845/npm/node_modules/tap/bin/run.js:127:3) {
   code: 'MODULE_NOT_FOUND',
   requireStack: [
     '/home/iojs/tmp/citgm_tmp/81754b80-27f7-459c-8dc8-8e0b3ae2f845/npm/node_modules/jackspeak/noop.js'
   ]
 }
 ```
 
Adding a reporter as suggested here resolves the issue.

Refs: https://github.com/nodejs/citgm/issues/852#issuecomment-815378553, https://github.com/nodejs/citgm/issues/852#issuecomment-816317278

**Comment by kraih** [comment]
I've also started seeing that error with Node 16:
```
> tap --no-coverage --no-esm test/*.js

Error: Cannot find module './reports/base'
Require stack:
- /Users/sri/repo/mojo.js/node_modules/jackspeak/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at resolveFileName (/Users/sri/repo/mojo.js/node_modules/tap/node_modules/resolve-from/index.js:17:39)
    at resolveFrom (/Users/sri/repo/mojo.js/node_modules/tap/node_modules/resolve-from/index.js:31:9)
    at module.exports (/Users/sri/repo/mojo.js/node_modules/tap/node_modules/resolve-from/index.js:34:41)
    at importJSX (/Users/sri/repo/mojo.js/node_modules/tap/node_modules/import-jsx/index.js:24:21)
    at module.exports (/Users/sri/repo/mojo.js/node_modules/tap/node_modules/treport/lib/index.js:13:18)
    at exports.makeReporter (/Users/sri/repo/mojo.js/node_modules/tap/bin/run.js:422:23)
    at runTests (/Users/sri/repo/mojo.js/node_modules/tap/bin/run.js:744:3)
    at mainAsync (/Users/sri/repo/mojo.js/node_modules/tap/bin/run.js:244:5)
    at main (/Users/sri/repo/mojo.js/node_modules/tap/bin/run.js:127:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/sri/repo/mojo.js/node_modules/jackspeak/noop.js' ]
}
```

**Comment by kraih** [comment]
I've also started seeing `Error: Cannot find module './reports/base'` with Node 16.
