### ISSUE TITLE
node-tap causes errors in node-jq execution.

### ISSUE THREAD

**Issue by jerrythomas** [tapjs/tapjs#669]
## Description

When running tests that use `node-jq` I am getting the following error

### sample code
No issues when run with `node index.js`
```js
const jq = require('node-jq');

async function convert(){
  const data = {a: 10};
  try {
    let result = await jq.run(".",
                              JSON.stringify(data),
                              { input: 'string' , output: 'json'});
    return result;
  } catch (err) {
    t.error(err)
  }
}
convert().then((res) => {
  console.log(res);
  process.exit()
})
```

### Test Source
This however runs into an issue. 

```js
const { test } = require('tap');
const jq = require('node-jq');

test('test jq', async t => {
  t.plan(1)
  const data = {a: 10};
  try {
    let result = await jq.run(".",
                              JSON.stringify(data),
                              { input: 'string' , output: 'json'});
    t.same(data, result)
  } catch (err) {
    t.error(err)
  }
});
```

### Error Message & Stack Trace

```text
test: jq.spec.js test jq
  origin:
    at:
      line: 462
      column: 3
      file: fs.js
      function: Object.openSync
    stack: |
      node_modules/node-jq/lib/exec.js:26:43
      new Promise (<anonymous>)
      exec (node_modules/node-jq/lib/exec.js:20:10)
      node_modules/node-jq/lib/jq.js:27:24
    errno: -13
    syscall: open
    code: EACCES
    path: /Users/Jerry/Code/experiments/jq-test/node_modules/node-jq/bin/jq
  found:
    !error
    name: Error
    message: "EACCES: permission denied, open
      '/Users/Jerry/Code/experiments/jq-test/node_modules/node-jq/bin/jq'"
    stack: >-
      Error:
          at Object.openSync (fs.js:462:3)
          at Proxy.readFileSync (fs.js:364:35)
          at mungeShebang (/usr/local/lib/node_modules/tap/node_modules/spawn-wrap/index.js:252:20)
          at munge (/usr/local/lib/node_modules/tap/node_modules/spawn-wrap/index.js:328:5)
          at ChildProcess.wrappedSpawn [as spawn] (/usr/local/lib/node_modules/tap/node_modules/spawn-wrap/index.js:89:5)
          at Proxy.spawn (child_process.js:548:9)
          at /Users/Jerry/Code/experiments/jq-test/node_modules/node-jq/lib/exec.js:26:43
          at new Promise (<anonymous>)
          at exec (/Users/Jerry/Code/experiments/jq-test/node_modules/node-jq/lib/exec.js:20:10)
          at /Users/Jerry/Code/experiments/jq-test/node_modules/node-jq/lib/jq.js:27:24
    errno: -13
    syscall: open
    code: EACCES
    path: /Users/Jerry/Code/experiments/jq-test/node_modules/node-jq/bin/jq
  stack: |
    Test.<anonymous> (jq.spec.js:13:7)
```
## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm/yarn, and node-jq.

Run the following to get it quickly:
nodejs version:
```bash
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
```
```
Node.js v13.13.0
darwin 19.4.0
```
yarn version: 
```bash
yarn --version
```
```
1.22.4
```
npm version:
```bash
npm --version
```
```
6.14.4
```
snippet from package.json
```
"dependencies": {
    "node-jq": "^1.11.0"
  },
  "devDependencies": {
    "tap": "^14.10.7"
  }
```

**Comment by coreyfarrell** [comment]
Can you please try adding `--no-coverage` to your `tap` command-line, see if this squashes the error?  I suspect this is some kind of incompatibility with nyc 14 and node-jq.  This is likely fixed by nyc 15 though for tap to upgrade nyc will be a semver-major change.

**Comment by jerrythomas** [comment]
Wow! you are right. When I run with `--no-coverage` it does eliminate the error. Thanks.

**Comment by coreyfarrell** [comment]
To get coverage with tap v14 you will have to install your own copy of `nyc@^15.0.0` and run with `nyc tap --no-coverage`.  This will run the copy of nyc you provided instead of using the one provided by tap.

Unfortunately this cannot be fixed in tap v14.

**Comment by jerrythomas** [comment]
Thank you @coreyfarrell for the workaround. I was able to get the coverage report using the command you provided.

**Comment by davesnx** [comment]
Hey @jerrythomas, Is there anything on the node-jq site that would fix it?

**Comment by coreyfarrell** [comment]
tap v15 is in beta and uses the updated version of nyc, could you test to see if this resolves your error without disabling coverage?
