### ISSUE TITLE
Extra configuration required to use tap with Typescript?

### ISSUE THREAD

**Issue by rogerta** [tapjs/tapjs#679]
The [Using with](https://node-tap.org/docs/using-with/) page suggest that to use tap with Typescript all you need to do is:
```
Name your test files .ts and they'll be loaded as TypeScript.
```
I think I've done just that but I get an error when the tests are run.  Can you let me know what I'm doing wrong?

Environment:
```
$ node --version
v12.18.1
$ npx tap --version
14.10.7
$ npx tsc --version
Version 3.9.5
```

Repro steps:
```
$ git clone https://github.com/rogerta/node-tap-ts.git
$ cd node-tap-ts/
$ npm install
$ npx tap
```

Error:
```
$ npx tap
foo.test.ts 2> (node:3528) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
foo.test.ts 2> /home/roger/src/test/foo.test.ts:1
foo.test.ts 2> import * as tap from 'tap';
foo.test.ts 2> ^^^^^^
foo.test.ts 2> 
foo.test.ts 2> SyntaxError: Cannot use import statement outside a module
foo.test.ts 2>     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
foo.test.ts 2>     at Module._compile (internal/modules/cjs/loader.js:1102:27)
foo.test.ts 2>     at Module.replacementCompile (/home/roger/src/test/node_modules/append-transform/index.js:58:13)
foo.test.ts 2>     at Module.m._compile (/home/roger/src/test/node_modules/ts-node/src/index.ts:858:23)
foo.test.ts 2>     at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
foo.test.ts 2>     at require.extensions.<computed> (/home/roger/src/test/node_modules/ts-node/src/index.ts:861:12)
foo.test.ts 2>     at Object.<anonymous> (/home/roger/src/test/node_modules/append-transform/index.js:62:4)
foo.test.ts 2>     at Module.load (internal/modules/cjs/loader.js:986:32)
foo.test.ts 2>     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
foo.test.ts 2>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
 FAIL  foo.test.ts 2s
  command: /usr/bin/node
  args:
    - -r
    - /home/roger/src/test/node_modules/ts-node/register/index.js
    - foo.test.ts
  exitCode: 1
  signal: null

 FAIL  TAP
 ✖ foo.test.ts

  test: TAP
  env:
    TS_NODE_COMPILER_OPTIONS: '{"jsx":"react"}'
  file: foo.test.ts
  timeout: 30000
  command: /usr/bin/node
  args:
    - -r
    - /home/roger/src/test/node_modules/ts-node/register/index.js
    - foo.test.ts
  stdio:
    - 0
    - pipe
    - 2
  cwd: /home/roger/src/test
  exitCode: 1

                         
  🌈 SUMMARY RESULTS 🌈  
                         

 FAIL  foo.test.ts 2s
  command: /usr/bin/node
  args:
    - -r
    - /home/roger/src/test/node_modules/ts-node/register/index.js
    - foo.test.ts
  exitCode: 1
  signal: null

Suites:   1 failed, 1 of 1 completed
Asserts:  1 failed, of 1
Time:     2s
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
```

The error message suggests two fixes.  Using an `.mjs` extension is not an option of course.  Trying the first suggestion leads to a different error:
```
$ npx tap
foo.test.ts 2> (node:3650) ExperimentalWarning: The ESM module loader is experimental.
foo.test.ts 2> TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /tmp/node-tap-ts/foo.test.ts
foo.test.ts 2>     at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:65:15)
foo.test.ts 2>     at Loader.getFormat (internal/modules/esm/loader.js:113:42)
foo.test.ts 2>     at Loader.getModuleJob (internal/modules/esm/loader.js:244:31)
foo.test.ts 2>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
foo.test.ts 2>     at Loader.import (internal/modules/esm/loader.js:178:17)
 FAIL  foo.test.ts 610.933ms
  command: /usr/bin/node
  args:
    - -r
    - /tmp/node-tap-ts/node_modules/ts-node/register/index.js
    - foo.test.ts
  exitCode: 1
  signal: null

 FAIL  TAP
 ✖ foo.test.ts

  test: TAP
  env:
    TS_NODE_COMPILER_OPTIONS: '{"jsx":"react"}'
  file: foo.test.ts
  timeout: 30000
  command: /usr/bin/node
  args:
    - -r
    - /tmp/node-tap-ts/node_modules/ts-node/register/index.js
    - foo.test.ts
  stdio:
    - 0
    - pipe
    - 2
  cwd: /tmp/node-tap-ts
  exitCode: 1


                         
  🌈 SUMMARY RESULTS 🌈

FAIL  foo.test.ts 610.933ms
  command: /usr/bin/node
  args:
    - -r
    - /tmp/node-tap-ts/node_modules/ts-node/register/index.js
    - foo.test.ts
  exitCode: 1
  signal: null

Suites:   1 failed, 1 of 1 completed
Asserts:  1 failed, of 1
Time:     797.793ms
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
```

**Comment by rogerta** [comment]
I was able to get the tests running correctly by switching the typescript module format to commonjs and making a [few other changes](https://github.com/rogerta/node-tap-ts/compare/commonjs?expand=1):
```
$ npx tap **/*.test.ts
foo.test.ts 1> foo
 PASS  foo.test.ts 1 OK 9.35ms

                         
  🌈 SUMMARY RESULTS 🌈  
                         

Suites:   1 passed, 1 of 1 completed
Asserts:  1 passed, of 1
Time:     2s
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
 foo.ts   |      100 |      100 |      100 |      100 |                   |
----------|----------|----------|----------|----------|-------------------|
```

Does this mean that tap won't work with typescript if using ECMA modules?  If so then maybe this should be added to the "Using with" page.  I also found the following were required for the tests to run cleanly.  Assuming I'm not holding it wrong it would be good to update the docs with this info too:

- Must use `import tap from 'tap'` and not `import * as tap from 'tap'`
- Must use `import './foo'` and not `import './foo.js'` or `import './foo.ts'`
- Must enable `esModuleInterop` typescript compiler option

More importantly for me though is whether it is possible to get tap working with typescript and ECMA module format since that is what my project uses.  Thanks.

**Comment by dchambers** [comment]
Handy list! Both times now I've also had to add `allowJs: false`, and most recently I also needed a set `files` to `true` for `ts-node`.

Altogether:

```
{
  "ts-node": {
    "files": true
  },
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "allowJs": false,
  }
}
```

**Comment by chakflying** [comment]
In addition to all those things, I had to explicitly run tap with `npx tap --ts` for it to run correctly. Without the `--ts` option, it loads the test but still gives the import error for some reason.

```json
    "tap": "^15.0.9",
    "ts-node": "^10.0.0",
    "typescript": "^4.3.5"
```

**Comment by gsouf** [comment]
> ```json
>     "tap": "^15.0.9",
>     "ts-node": "^10.0.0",
>     "typescript": "^4.3.5"
> ```

I second this. Had to explicitly add "typescript" as a dependency of the project and add the `--ts` tag to get it working. All of the other solutions proposed above were unnecessary for me.

**Comment by balexandre** [comment]
I must say that also I am struggling to start with `tap`, even created a simple project that shows the `Unknown file extension ".ts"` when trying to run, can anyone provide me some light on what am I doing wrong?

https://github.com/balexandre/testing-tap

**Comment by isaacs** [comment]
Yeah, a lot of things have changed, and unfortunately I'd been too busy to keep up.  The next version of tap (currently in very active development, see: #821) will make things work out of the box again with TS and ESM.

In the meantime, here's what I'm doing:

Use c8 for coverage, ts-node for running files, and the `@types/tap` type defs:

```
npm install --save-dev tap@latest c8 @types/tap ts-node
```

Update your package.json to tell tap _not_ to try to load its own ts-node or use nyc for coverage, since they are broken in later versions of node, and instead to run the tests/snapshot commands prefixed with `c8`.

```json
{
  "tap": {
    "coverage": false,
    "node-arg": [
      "--no-warnings",
      "--loader",
      "ts-node/esm"
    ],
    "ts": false
  },
  "scripts": {
    "test": "c8 tap",
    "snap": "c8 tap"
  }
}
```

Then you can just write tests in typescript as normal, load your modules, etc.

**Comment by balexandre** [comment]
got it working and [updated the repo](https://github.com/balexandre/testing-tap) with the correct configuration so it can help someone else...

thank you so much for the prompt reply! 

it's now time to dig deeper 😁👌

**Comment by bigicoin** [comment]
Thanks for this repo, @balexandre ! Just want to say that it helped me out.

**Comment by isaacs** [comment]
Typescript is first class citizen in tap 18. `npm i tap@pre` https://node-tap.org/changelog/#18.0
