### ISSUE TITLE
tap not catching errors in async code

### ISSUE THREAD

**Issue by mcavage** [tapjs/tapjs#7]
The code below will dump:

```
bluesnoop:node-ldap mark$ node tst/fail.test.js 

/Users/mark/work/node-ldap/tst/fail.test.js:25
    t.ok(files[0]);
              ^
TypeError: Cannot read property '0' of undefined
    at /Users/mark/work/node-ldap/tst/fail.test.js:25:15
    at /Users/mark/work/node-ldap/tst/fail.test.js:8:14
bluesnoop:node-ldap mark$ 
```

```
var fs = require('fs');
var test = require('tap').test;


function ls(dir, callback) {
  fs.readdir(dir, function(err, files) {
    if (err)
      return callback(new Error(err.message));

    return callback(null, files);
  });
}


test('tap not catching error', function(t) {
  ls('/_tmp', function(err, files) {
    t.ok(files[0]);
    t.end();
  });
});
```

**Comment by isaacs** [comment]
Ok, here's how to do this:

In GlobalHarness.test, set up a `process.on("uncaughtException")` handler.  If it catches anything, then bail out immediately.

**Comment by sam-github** [comment]
Behaviour is as I expect. Run with the `tap` runner and it will see the test aborted with non-zero exit status and mark the test as failed. When running with node, tap hides nothing - perfect for debugging and development of the unit test.
