### ISSUE TITLE
Warning when using tap/mocha

### ISSUE THREAD

**Issue by julien-f** [tapjs/tapjs#831]
`index.spec.js`:
```js
require('tap/mocha')
```

Output:
```
> node --trace-warnings index.spec.js
(node:54310) Warning: Accessing non-existent property 'global' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object.<anonymous> (test/node_modules/tap/lib/tap.js:10:30)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (test/node_modules/tap/lib/mocha.js:2:11)
```

The problem does not occur when using `require('tap').mocha`.

**Comment by brupelo** [comment]
This issue seems to be highly related to [https://github.com/tapjs/node-tap/issues/835](https://github.com/tapjs/node-tap/issues/835)

**Comment by isaacs** [comment]
No longer relevant on tap v18. Next release will have `@tapjs/mocha-globals` plugin that can be used, and there's no problems with cycles.
