### ISSUE TITLE
Warning: Accessing non-existent property 'global' of module exports inside circular dependency

### ISSUE THREAD

**Issue by brupelo** [tapjs/tapjs#835]
Consider this little mcve:

```
$ cat test.js
import { describe, it } from "tap/lib/mocha.js";

$ cat package.json
{
  "name": "mcve_tap",
  "version": "1.0.0",
  "description": "",
  "main": "test.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "tap": "^16.3.0"
  },
  "type": "module"
}
```

If I run that test I'll get this warning:

```
$ node --trace-warnings test.js
(node:15784) Warning: Accessing non-existent property 'global' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object.<anonymous> (d:\mcve_tap\node_modules\tap\lib\tap.js:10:30)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (d:\mcve_tap\node_modules\tap\lib\mocha.js:2:11)
```

So my question is, how am I supposed to run "Mocha-like DSL" on my project which is using `esm` modules? In the docs  [https://node-tap.org/docs/api/mochalike/](https://node-tap.org/docs/api/mochalike/) it's only explained how to use with `cjs` modules through `require`

Taking a look to all exports from "tap" I don't see neither the `mochaGlobals` exposed or the mocha object, ie:

```
[Module: null prototype] {
  Spawn: [class Spawn extends Base] { procName: [Function (anonymous)] },
  Stdin: [class Stdin extends Base],
  Test: [class Test extends Base],
  addAssert: [Function: bound addAssert],
  afterEach: [Function: bound afterEach],
  autoend: [Function: bound autoend],
  bailout: [Function: bound bailout],
  beforeEach: [Function: bound beforeEach],
  comment: [Function: bound comment],
  default: TAP {
    name: 'TAP',
    time: null,
    hrtime: null,
    jobs: 1,
    buffered: false,
    occupied: false,
    pool: Set(0) {},
    queue: [ 'TAP version 13\n' ],
    subtests: [],
    output: '',
    skip: false,
    todo: false,
    only: false,
    results: null,
    options: {}
  },
  doesNotThrow: [Function: bound doesNotThrow],
  emits: [Function: bound emits],
  end: [Function: bound end],
  equal: [Function: bound equal],
  error: [Function: bound error],
  expectUncaughtException: [Function: bound expectUncaughtException],
  fail: [Function: bound fail],
  fixture: [Function: bound fixture],
  hasStrict: [Function: bound hasStrict],
  main: [Function: bound main],
  match: [Function: bound match],
  matchSnapshot: [Function: bound matchSnapshot],
  not: [Function: bound not],
  notMatch: [Function: bound notMatch],
  notOk: [Function: bound notOk],
  notSame: [Function: bound notSame],
  ok: [Function: bound ok],
  only: [Function: bound only],
  pass: [Function: bound pass],
  plan: [Function: bound plan],
  pragma: [Function: bound pragma],
  process: [Function: bound process],
  processSubtest: [Function: bound processSubtest],
  rejects: [Function: bound rejects],
  resolveMatch: [Function: bound resolveMatch],
  resolveMatchSnapshot: [Function: bound resolveMatchSnapshot],
  resolves: [Function: bound resolves],
  same: [Function: bound same],
  skip: [Function: bound skip],
  spawn: [Function: bound spawn],
  stdin: [Function: bound stdin],
  stdinOnly: [Function: bound stdinOnly],
  strictNotSame: [Function: bound strictNotSame],
  strictSame: [Function: bound strictSame],
  sub: [Function: bound sub],
  teardown: [Function: bound teardown],
  test: [Function: bound test],
  testdir: [Function: bound testdir],
  throws: [Function: bound throws],
  throwsArgs: [Function: bound throwsArgs],
  timeout: [Function: bound timeout],
  todo: [Function: bound todo],
  type: [Function: bound type]
}
```

Which makes sense as basically I'm seeing the content exported from `tap.mjs`:

```
import tap from './tap.js'

export const {
  Test, Spawn, Stdin,
  spawn, sub,
  todo, skip, only, test,
  stdinOnly, stdin,
  bailout,
  comment,
  timeout,
  main,
  process,
  processSubtest,
  addAssert,
  pragma,
  plan, end,
  beforeEach,
  afterEach,
  teardown,
  autoend,
  pass, fail, ok, notOk,
  emits,
  error, equal, not, same, notSame, strictSame, strictNotSame,
  testdir, fixture,
  matchSnapshot,
  hasStrict, match, notMatch, type,
  expectUncaughtException, throwsArgs, throws, doesNotThrow,
  rejects, resolves, resolveMatch, resolveMatchSnapshot
} = tap

export default tap
```

Could you please advice? What's the proper way to use mocha syntax with node projects using `type: "module"`  without getting any warnings? 

Thanks in advance.

**Comment by isaacs** [comment]
Old mocha globals are no longer supported. It'll come back with a plugin soon, and much more strictness from esm and ts.
