### ISSUE TITLE
ERR_UNKNOWN_FILE_EXTENSION

### ISSUE THREAD

**Issue by tommarien** [tapjs/tapjs#938]
tap: latest published version: 18.14.2
node: v18.18.0

```
▶ npm t **/src/*.test.ts

> ts-node-api-2023@1.0.0 test
> tap src/index.test.ts

 SKIP  src/index.test.ts 0 OK 131ms
 ~ no tests found

2> src/index.test.ts
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/tommarien/git/tommarien/ts-node-api-2023/src/index.test.ts
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:124:36)
    at defaultLoad (node:internal/modules/esm/load:89:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at load (/Users/tommarien/git/tommarien/ts-node-api-2023/node_modules/@tapjs/processinfo/src/hooks.mts:121:21)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at load (/Users/tommarien/git/tommarien/ts-node-api-2023/node_modules/@tapjs/mock/src/hooks.mts:47:7)
    at async nextLoad (node:internal/modules/esm/loader:163:22)
    at load (/Users/tommarien/git/tommarien/ts-node-api-2023/node_modules/@tapjs/processinfo/src/hooks.mts:121:15)
    at async nextLoad (node:internal/modules/esm/loader:163:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:603:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:11)
    at async link (node:internal/modules/esm/module_job:68:21) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Node.js v18.18.0
```

package.json
```
  "type": "module",
  "engines": {
    "node": "18.x"
  },
  "scripts": {
    "test": "tap"
  },
  "author": "Tom Marien",
  "license": "ISC",
  "devDependencies": {
    "@tsconfig/node18": "^18.2.2",
    "@types/node": "^18.18.1",
    "prettier": "^3.0.3",
    "tap": "^18.4.2",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
  }

```

running `node --loader=ts-node/esm ./src/index.test.ts` does produce output

What am i missing that its seems that tap does not autoinclude the loader ?

**Comment by isaacs** [comment]
That's really odd.

What does this output?  `tap plugin list`  Make sure that `@tapjs/typescript` is on the list.

Also, what do you have in `tap config list`?

Last thing worth checking, run with `tap -Rtap --debug src/index.test.ts`, and look for the `args: ` section where it spits out the arguments it's passing to node. (I wouldn't just dump the whole debug output to a gist or something, though, because it dumps the env as well, been meaning to make it not do that.)

**Comment by isaacs** [comment]
Almost certainly not not related, but should the command be `npm t src/**/*.test.ts`? The way you have it here, it's searching everywhere for a folder called `src`, you probably don't want to bother running tests in `node_modules/some/dep/src/...`

**Comment by isaacs** [comment]
The only thing that jumps out is that you depend  directly on `ts-node`, so it might be picking up the distributed version of that, and not the version that I forked to work on node 20.

I probably need to make tap just depend on the forked module explicitly, rather than doing `ts-node@npm:@isaacs/ts-node-temporary-fork-for-pr-2009`, otherwise package managers tend to get clever and think they're the same thing.

**Comment by tommarien** [comment]
output of tap plugin list

```
▶ npx tap plugin list
@tapjs/after
@tapjs/after-each
@tapjs/asserts
@tapjs/before
@tapjs/before-each
@tapjs/filter
@tapjs/fixture
@tapjs/intercept
@tapjs/mock
@tapjs/node-serialize
@tapjs/snapshot
@tapjs/spawn
@tapjs/stdin
@tapjs/typescript
@tapjs/worker

```

output of debug

```
Node.js v18.18.0
TAP 25117 src/index.test.ts: LINE "TAP version 14\n" [ 'src/index.test.ts', '    ' ]
TAP 25117 TAP: LINE "# Subtest: src/index.test.ts\n" [ 'TAP', '' ]
# Subtest: src/index.test.ts
TAP 25117 src/index.test.ts: LINE "1..0 # no tests found\n" [ 'src/index.test.ts', '    ' ]
TAP 25117 TAP: LINE "    1..0 # no tests found\n" [ 'TAP', '' ]
    1..0 # no tests found
TAP 25117 src/index.test.ts: ONCOMPLETE "src/index.test.ts" {"ok":true,"count":0,"pass":0,"fail":0,"bailout":false,"todo":0,"skip":0,"failures":[],"time":null,"plan":{"start":1,"end":0,"skipAll":true,"skipReason":"no tests found","comment":"no tests found"},"skips":[],"todos":[]}
TAP 25117 src/index.test.ts: SPAWN close 1 null
TAP 25117 TAP: onIndentedEnd src/index.test.ts
TAP 25117 TAP: #onIndentedEnd TAP(src/index.test.ts)
TAP 25117 TAP: OIE(TAP) >shift into queue []
TAP 25117 TAP: LINE "not ok 1 - src/index.test.ts # time=191.158ms\n" [ 'TAP', '' ]
not ok 1 - src/index.test.ts # time=191.158ms
TAP 25117 TAP: LINE "  ---\n" [ 'TAP', '' ]
  ---
TAP 25117 TAP: LINE "  stdio: inherit\n" [ 'TAP', '' ]
  stdio: inherit
TAP 25117 TAP: LINE "  cwd: /Users/tommarien/git/tommarien/ts-node-api-2023\n" [ 'TAP', '' ]
  cwd: /Users/tommarien/git/tommarien/ts-node-api-2023
TAP 25117 TAP: LINE "  externalID: src/index.test.ts\n" [ 'TAP', '' ]
  externalID: src/index.test.ts
TAP 25117 TAP: LINE "  command: /Users/tommarien/Library/Application\n" [ 'TAP', '' ]
  command: /Users/tommarien/Library/Application
TAP 25117 TAP: LINE "    Support/fnm/node-versions/v18.18.0/installation/bin/node\n" [ 'TAP', '' ]
    Support/fnm/node-versions/v18.18.0/installation/bin/node
TAP 25117 TAP: LINE "  args:\n" [ 'TAP', '' ]
  args:
TAP 25117 TAP: LINE "    - --loader=file:///Users/tommarien/git/tommarien/ts-node-api-2023/node_modules/@tapjs/mock/dist/esm/legacy-loader.mjs\n" [ 'TAP', '' ]
    - --loader=file:///Users/tommarien/git/tommarien/ts-node-api-2023/node_modules/@tapjs/mock/dist/esm/legacy-loader.mjs
TAP 25117 TAP: LINE "    - --no-warnings\n" [ 'TAP', '' ]
    - --no-warnings
TAP 25117 TAP: LINE "    - --enable-source-maps\n" [ 'TAP', '' ]
    - --enable-source-maps
TAP 25117 TAP: LINE "    - --loader=file:///Users/tommarien/git/tommarien/ts-node-api-2023/node_modules/@tapjs/processinfo/dist/esm/loader-legacy.mjs\n" [ 'TAP', '' ]
    - --loader=file:///Users/tommarien/git/tommarien/ts-node-api-2023/node_modules/@tapjs/processinfo/dist/esm/loader-legacy.mjs
TAP 25117 TAP: LINE "    - /Users/tommarien/git/tommarien/ts-node-api-2023/src/index.test.ts\n" [ 'TAP', '' ]
    - /Users/tommarien/git/tommarien/ts-node-api-2023/src/index.test.ts
TAP 25117 TAP: LINE "  context: !symbol/shared tap.isRunner\n" [ 'TAP', '' ]
  context: !symbol/shared tap.isRunner
TAP 25117 TAP: LINE "  debug: true\n" [ 'TAP', '' ]
  debug: true
TAP 25117 TAP: LINE "  exitCode: 1\n" [ 'TAP', '' ]
  exitCode: 1
TAP 25117 TAP: LINE "  signal: null\n" [ 'TAP', '' ]
  signal: null
TAP 25117 TAP: LINE "  ...\n" [ 'TAP', '' ]
  ...
TAP 25117 TAP: LINE "\n" [ 'TAP', '' ]

TAP 25117 TAP: END TAP implicit=true
TAP 25117 TAP: push obe
TAP 25117 TAP: set ended=true
TAP 25117 TAP: PROCESSING(TAP) 1
TAP 25117 TAP: > EOF TAP
TAP 25117 TAP: call onEOF TAP
TAP 25117 TAP: onEOF is promise
TAP 25117 TAP: < already processing
TAP 25117 TAP: done processing [
TAP 25117 TAP:   Waiter {
TAP 25117 TAP:     cb: [Function (anonymous)],
TAP 25117 TAP:     ready: false,
TAP 25117 TAP:     value: undefined,
TAP 25117 TAP:     resolved: false,
TAP 25117 TAP:     rejected: false,
TAP 25117 TAP:     done: false,
TAP 25117 TAP:     finishing: false,
TAP 25117 TAP:     expectReject: false,
TAP 25117 TAP:     promise: Promise {
TAP 25117 TAP:       <pending>,
TAP 25117 TAP:       [Symbol(async_id_symbol)]: 1880,
TAP 25117 TAP:       [Symbol(trigger_async_id_symbol)]: 1846
TAP 25117 TAP:     },
TAP 25117 TAP:     resolve: [Function (anonymous)]
TAP 25117 TAP:   }
TAP 25117 TAP: ] null
TAP 25117 TAP: PROCESSING(TAP) 1
TAP 25117 TAP: done processing [] Waiter {
TAP 25117 TAP:   cb: [Function (anonymous)],
TAP 25117 TAP:   ready: true,
TAP 25117 TAP:   value: undefined,
TAP 25117 TAP:   resolved: false,
TAP 25117 TAP:   rejected: false,
TAP 25117 TAP:   done: false,
TAP 25117 TAP:   finishing: false,
TAP 25117 TAP:   expectReject: false,
TAP 25117 TAP:   promise: Promise {
TAP 25117 TAP:     <pending>,
TAP 25117 TAP:     [Symbol(async_id_symbol)]: 1880,
TAP 25117 TAP:     [Symbol(trigger_async_id_symbol)]: 1846
TAP 25117 TAP:   },
TAP 25117 TAP:   resolve: [Function (anonymous)]
TAP 25117 TAP: }
TAP 25117 TAP: PROCESSING(TAP) 0
TAP 25117 TAP: done processing [] Waiter {
TAP 25117 TAP:   cb: [Function (anonymous)],
TAP 25117 TAP:   ready: true,
TAP 25117 TAP:   value: undefined,
TAP 25117 TAP:   resolved: false,
TAP 25117 TAP:   rejected: false,
TAP 25117 TAP:   done: false,
TAP 25117 TAP:   finishing: false,
TAP 25117 TAP:   expectReject: false,
TAP 25117 TAP:   promise: Promise {
TAP 25117 TAP:     <pending>,
TAP 25117 TAP:     [Symbol(async_id_symbol)]: 1880,
TAP 25117 TAP:     [Symbol(trigger_async_id_symbol)]: 1846
TAP 25117 TAP:   },
TAP 25117 TAP:   resolve: [Function (anonymous)]
TAP 25117 TAP: }
TAP 25117 TAP: OIE(TAP) shifted into queue []
TAP 25117 TAP: PROCESSING(TAP) 0
TAP 25117 TAP: done processing [] Waiter {
TAP 25117 TAP:   cb: [Function (anonymous)],
TAP 25117 TAP:   ready: true,
TAP 25117 TAP:   value: undefined,
TAP 25117 TAP:   resolved: false,
TAP 25117 TAP:   rejected: false,
TAP 25117 TAP:   done: false,
TAP 25117 TAP:   finishing: false,
TAP 25117 TAP:   expectReject: false,
TAP 25117 TAP:   promise: Promise {
TAP 25117 TAP:     <pending>,
TAP 25117 TAP:     [Symbol(async_id_symbol)]: 1880,
TAP 25117 TAP:     [Symbol(trigger_async_id_symbol)]: 1846
TAP 25117 TAP:   },
TAP 25117 TAP:   resolve: [Function (anonymous)]
TAP 25117 TAP: }
# No coverage generated
TAP 25117 TAP: run/report exit=1 coverage is empty CoverageSummary {
TAP 25117 TAP:   data: {
TAP 25117 TAP:     lines: { total: 0, covered: 0, skipped: 0, pct: 'Unknown' },
TAP 25117 TAP:     statements: { total: 0, covered: 0, skipped: 0, pct: 'Unknown' },
TAP 25117 TAP:     functions: { total: 0, covered: 0, skipped: 0, pct: 'Unknown' },
TAP 25117 TAP:     branches: { total: 0, covered: 0, skipped: 0, pct: 'Unknown' },
TAP 25117 TAP:     branchesTrue: { total: 0, covered: 0, skipped: 0, pct: 'Unknown' }
TAP 25117 TAP:   }
TAP 25117 TAP: }
TAP 25117 TAP: PROCESSING(TAP) 1
TAP 25117 TAP: done processing [ Symbol(EOF) ] Waiter {
TAP 25117 TAP:   cb: [Function (anonymous)],
TAP 25117 TAP:   ready: true,
TAP 25117 TAP:   value: undefined,
TAP 25117 TAP:   resolved: true,
TAP 25117 TAP:   rejected: false,
TAP 25117 TAP:   done: true,
TAP 25117 TAP:   finishing: true,
TAP 25117 TAP:   expectReject: false,
TAP 25117 TAP:   promise: Promise {
TAP 25117 TAP:     <pending>,
TAP 25117 TAP:     [Symbol(async_id_symbol)]: 1880,
TAP 25117 TAP:     [Symbol(trigger_async_id_symbol)]: 1846
TAP 25117 TAP:   },
TAP 25117 TAP:   resolve: [Function (anonymous)]
TAP 25117 TAP: }
TAP 25117 TAP: PROCESSING(TAP) 1
TAP 25117 TAP: > EOF TAP
TAP 25117 TAP: eof end parser TAP
TAP 25117 TAP: ONCOMPLETE "TAP" {"ok":false,"count":1,"pass":0,"fail":1,"bailout":false,"todo":0,"skip":0,"failures":[{"ok":false,"name":"src/index.test.ts","id":1,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"stdio":"inherit","cwd":"/Users/tommarien/git/tommarien/ts-node-api-2023","externalID":"src/index.test.ts","command":"/Users/tommarien/Library/Application Support/fnm/node-versions/v18.18.0/installation/bin/node","args":["--loader=file:///Users/tommarien/git/tommarien/ts-node-api-2023/node_modules/@tapjs/mock/dist/esm/legacy-loader.mjs","--no-warnings","--enable-source-maps","--loader=file:///Users/tommarien/git/tommarien/ts-node-api-2023/node_modules/@tapjs/processinfo/dist/esm/loader-legacy.mjs","/Users/tommarien/git/tommarien/ts-node-api-2023/src/index.test.ts"],"debug":true,"exitCode":1,"signal":null},"time":191.158,"fullname":"TAP > src/index.test.ts"}],"time":null,"plan":{"start":1,"end":1,"skipAll":false,"skipReason":"","comment":""},"skips":[],"todos":[]}
# { total: 1, pass: 0, fail: 1 }
# time=225.791ms
TAP 25117 TAP: TAP results not ok, setting exitCode FinalResults {
TAP 25117 TAP:   ok: false,
TAP 25117 TAP:   count: 1,
TAP 25117 TAP:   pass: 0,
TAP 25117 TAP:   fail: 1,
TAP 25117 TAP:   bailout: false,
TAP 25117 TAP:   todo: 0,
TAP 25117 TAP:   skip: 0,
TAP 25117 TAP:   failures: [
TAP 25117 TAP:     Result {
TAP 25117 TAP:       ok: false,
TAP 25117 TAP:       name: 'src/index.test.ts',
TAP 25117 TAP:       id: 1,
TAP 25117 TAP:       buffered: false,
TAP 25117 TAP:       tapError: null,
TAP 25117 TAP:       skip: false,
TAP 25117 TAP:       todo: false,
TAP 25117 TAP:       previous: null,
TAP 25117 TAP:       plan: null,
TAP 25117 TAP:       diag: [Object],
TAP 25117 TAP:       time: 191.158,
TAP 25117 TAP:       fullname: 'TAP > src/index.test.ts'
TAP 25117 TAP:     }
TAP 25117 TAP:   ],
TAP 25117 TAP:   time: null,
TAP 25117 TAP:   passes: undefined,
TAP 25117 TAP:   plan: FinalPlan {
TAP 25117 TAP:     start: 1,
TAP 25117 TAP:     end: 1,
TAP 25117 TAP:     skipAll: false,
TAP 25117 TAP:     skipReason: '',
TAP 25117 TAP:     comment: ''
TAP 25117 TAP:   },
TAP 25117 TAP:   skips: [],
TAP 25117 TAP:   todos: []
TAP 25117 TAP: }
TAP 25117 TAP: > end of queue
TAP 25117 TAP: done processing [] null
TAP 25117 TAP: END TAP implicit=true
TAP 25117 TAP: already ended, ignore implicit end

```

**Comment by tommarien** [comment]
@isaacs i am on node 18(lts)

**Comment by isaacs** [comment]
Yeah, sure enough, the ts-node loader is just gone missing.

Try this:

```
node -p 'require("tap"); require("@tapjs/test").loaderFallbacks'
```

That should have `ts-node/esm` in the list. (Or really, it _shouldn't_, if it's there in that list but not being used, then witaf?)

If it's not, then `tap build` might fix the problem, but I'm super perplexed about how it could have happened in the first place. Any chance you could `tar czf node_modules.tgz node_modules` before doing that?  If you have private code in there, you could just run `tar zvf node_modules.tgz node_modules/{@tapjs,ts-node}` which would probably get me what I need to reproduce it.

If running `tap build` _doesn't_ fix it, nuclear option:

```
mv node_modules{,.bak}
# if using a lockfile:
mv package-lock.json{,.bak}
npm install
```

**Comment by isaacs** [comment]
Oh, another thing to check, probably not the issue but might shake something else loose if it errors or something:

```
npm ls @tapjs/typescript
node -p 'require("@tapjs/typescript").loader'
```

**Comment by tommarien** [comment]
output (so indeed not there):
```
▶ node -p 'require("tap"); require("@tapjs/test").loaderFallbacks'
[ '@tapjs/mock/loader' ]

```

after tap build:

```
▶ npx tap ./src/**/*.test.ts
 SKIP  src/index.test.ts 0 OK 292ms
 ~ no tests found


  🌈 TEST COMPLETE 🌈


Asserts:  0 pass  0 fail  1 skip  0 of 1 complete
Suites:   0 pass  0 fail  1 skip  0 of 1 complete

# No coverage generated
# { total: 1, pass: 0, skip: 1 }
# time=341.388ms

```

**Comment by isaacs** [comment]
So `tap build` fixed it? (Or are there actually tests in there that aren't being run? 😅)

Was there a build failure when you installed it? I'm so curious, never seen that happen.

**Comment by tommarien** [comment]
@isaacs no it does not run the test anymore, so it did not fix anything, it actually made it worse :(

**Comment by tommarien** [comment]
@isaacs if you want i can create a simple github repo with the example?

**Comment by tommarien** [comment]
```
▶ npm ls @tapjs/typescript
ts-node-api-2023@1.0.0 /Users/tommarien/git/tommarien/ts-node-api-2023
└─┬ tap@18.4.2
  ├─┬ @tapjs/test@1.3.6
  │ └── @tapjs/typescript@1.2.6 deduped
  └── @tapjs/typescript@1.2.6
```

```
▶ node -p 'require("@tapjs/typescript").loader'
ts-node/esm
```

**Comment by tommarien** [comment]
after some rechecking, yes tap build fixed it, did a wrong copy paste of one of the commands you gave, thanks for the assist, i'll try again, from scratch to verify that i can reproduce it, and that 'tap build' fixes it, although i do not know why?

**Comment by tommarien** [comment]
@isaacs tried again clean slate no issue 🤷 , again thanks for the help
