### ISSUE TITLE
`tap` seems to fail due to TS and modules

### ISSUE THREAD

**Issue by ydennisy** [tapjs/tapjs#946]
Hi!

I am using tap on a small project succesfully, but now trying to swap out jest on a larger node + ts project and the unable to run a single test, here is the error:

```
npm test

> app-backend@0.0.179 test
> tap run

 SKIP  src/modules/labs/use-case/define-demographic-audience/define-demographic-audience.test.ts 0 OK 270ms
 ~ no tests found

2> src/modules/labs/use-case/define-demographic-audience/define-demographic-audience.test.ts
/Users/dennis/dev/studio/backend/src/modules/labs/use-case/define-demographic-audience/define-demographic-audience.test.ts:1
import t from 'tap';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1205:27)
    at Module._compile (/Users/dennis/dev/studio/backend/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.newLoader [as .ts] (/Users/dennis/dev/studio/backend/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at cjsLoader (node:internal/modules/esm/translators:284:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:234:7)

Node.js v20.8.0


  🌈 TEST COMPLETE 🌈


 FAIL  src/modules/labs/use-case/define-demographic-audience/define-demographic-audience.test.ts 0 270ms

Asserts:  0 pass  1 fail  1 of 1 complete
Suites:   0 pass  1 fail  1 of 1 complete

# No coverage generated
# { total: 1, pass: 0, fail: 1 }
# time=352.073ms
```

Here is my TS config:

```json
{
  "compilerOptions": {
    "lib": ["ES2023"],
    "module": "commonjs",
    "target": "ES2022",
    "rootDir": "./",
    "outDir": "./build",
    "esModuleInterop": true,
    "moduleResolution": "node",
    "strict": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "noImplicitAny": true,
    "noImplicitOverride": true,
    "noUncheckedIndexedAccess": true,
    "resolveJsonModule": true
  },
  "exclude": ["node_modules", "**/*.test.ts"]
}
```

And the test file:

```ts
import t from 'tap';
import { DefineDemographicAudience } from './define-demographic-audience';
import { postalSectorFeaturesRepo } from '../../repos';

const defineDemographicAudience = new DefineDemographicAudience(postalSectorFeaturesRepo);

t.test('this is a child test', async t => {
  const response = await defineDemographicAudience.execute({features:[""]})

  t.equal(response, 42)
  t.end()
})
```

I am using tap 18.4.3 and node 20 and running with `tap run`.

Any ideas why it seems to be failing to use modules?

**Comment by isaacs** [comment]
Can you run with `-Rtap`, or share a file from .tap/test-results?

It seems like it's not loading the code through the typescript transpiler.

**Comment by ydennisy** [comment]
Hey @isaacs - thanks for the quick reply :)

Sure!!

```
npx tap run -Rtap
TAP version 14
1..1
/Users/dennis/dev/studio/backend/src/modules/labs/use-case/define-demographic-audience/define-demographic-audience.test.ts:1
import t from 'tap';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1205:27)
    at Module._compile (/Users/dennis/dev/studio/backend/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.newLoader [as .ts] (/Users/dennis/dev/studio/backend/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at cjsLoader (node:internal/modules/esm/translators:284:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:234:7)

Node.js v20.8.0
# Subtest: src/modules/labs/use-case/define-demographic-audience/define-demographic-audience.test.ts
    1..0 # no tests found
not ok 1 - src/modules/labs/use-case/define-demographic-audience/define-demographic-audience.test.ts # time=271.122ms
  ---
  stdio: inherit
  cwd: /Users/dennis/dev/studio/backend
  externalID: src/modules/labs/use-case/define-demographic-audience/define-demographic-audience.test.ts
  command: /Users/dennis/.nvm/versions/node/v20.8.0/bin/node
  args:
    - --import=file:///Users/dennis/dev/studio/backend/node_modules/@tapjs/mock/dist/esm/import.mjs
    - --loader=file:///Users/dennis/dev/studio/backend/node_modules/ts-node/esm.mjs
    - --no-warnings
    - --enable-source-maps
    - --import=file:///Users/dennis/dev/studio/backend/node_modules/@tapjs/processinfo/dist/esm/import.mjs
    - /Users/dennis/dev/studio/backend/src/modules/labs/use-case/define-demographic-audience/define-demographic-audience.test.ts
  context: !symbol/shared tap.isRunner
  exitCode: 1
  signal: null
  ...

# No coverage generated
# { total: 1, pass: 0, fail: 1 }
# time=322.546ms
```

The file in `.tap/test-results/src/modules/labs/use-case/define-demographic-audience/define-demographic-audience.test.ts.tap` is empty.

**Comment by isaacs** [comment]
Hm, so it's running with the ts-node loader. 

What do you see if you run this command?

```
node --loader=ts-node/esm src/modules/labs/use-case/define-demographic-audience/define-demographic-audience.test.ts
```

**Comment by isaacs** [comment]
Oh! Your test file is excluded by your tsconfig, that could be it.

If you remove `**/*.test.ts` from tsconfig's excludes, does it work then?

If so, you can create a `tsconfig.build.json` containing the exclude and `"extends":"./tsconfig.json"`, and run your production builds with `tsc -p tsconfig.build.json` to use it there but leave the files covered for tests and such.

**Comment by isaacs** [comment]
You can also provide a custom tsconfig for use by tap with the `--tsconfig=<file>` tap config option.

**Comment by isaacs** [comment]
(closing just to move it off my todo list, happy to reopen when/if more details provided, especially if there's a bug here)

**Comment by ydennisy** [comment]
hey @isaacs really sorry for the delay in replying - I was off for two weeks :)

Thanks again for the really quick and detailed replies it is hugely appreciated!

---

Ok so I tried to run my personal project which does not have the issue you pointed out (doughhh!) and it threw the same error! So I guess this is due to the node version which I bumped across all projects at once. 

I have tried to bump the `tap` version to `18.5.2` and now have a new error:

```
dennis@LDN-DennisYurkevich# backend % npx tap
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^

[Error: Package subpath './generate-tap-test-class' is not defined by "exports" in /Users/dennis/dev/kg1/backend/node_modules/@tapjs/test/package.json imported from /Users/dennis/dev/kg1/backend/x] {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v20.8.0
```

I will try and downgrade node back to `v16` to try and see if that resolves the issue and update here!

Here is my `tsconfig` on the small side project where all was well:

```json
{
  "compilerOptions": {
    "target": "es2022",
    "lib": ["es2023"],
    "module": "node16", 
    "moduleResolution": "node16",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
}
```

**Comment by isaacs** [comment]
@ydennisy Ok, something is messed up. That subpath definitely is exported: https://github.com/tapjs/tapjs/blob/main/src/test/package.json#L30

So you must have some mismatched versions of something somewhere.

What do these commands output?

```
npm ls tap @tapjs/test
tap plugin list
tap config list
tap versions
```

**Comment by ydennisy** [comment]
Hey @isaacs :), thanks for the reply - please see below.

```
npm ls tap @tapjs/test

kg1@0.0.1 /Users/dennis/dev/kg1/backend
├─┬ @tapjs/node-serialize@1.0.0
│ └─┬ @tapjs/core@1.1.0
│   └── @tapjs/test@1.1.0
└─┬ tap@18.5.2
  ├─┬ @tapjs/core@1.4.2
  │ └── @tapjs/test@1.3.13 deduped
  ├─┬ @tapjs/run@1.4.9
  │ ├─┬ @tapjs/config@2.4.9
  │ │ ├─┬ @tapjs/core@1.4.2
  │ │ │ └── @tapjs/test@1.3.13 deduped
  │ │ └── @tapjs/test@1.3.13
  │ └── @tapjs/test@1.3.13 deduped
  └── @tapjs/test@1.3.13
```

```
npx tap plugin list

node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^

[Error: Package subpath './generate-tap-test-class' is not defined by "exports" in /Users/dennis/dev/kg1/backend/node_modules/@tapjs/test/package.json imported from /Users/dennis/dev/kg1/backend/x] {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v20.9.0
```

```
npx tap config list

# vim: set filetype=yaml :
color: true
coverage-report:
  - text
exclude:
  - "**/@(fixture*(s)|dist)/**"
include:
  - "**/@(test?(s)|__test?(s)__)/**/*.@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/*.@(test?(s)|spec).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/test?(s).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
jobs: 9
reporter: base
snapshot-clean-cwd: true
timeout: 30
```

```
npx tap versions

/Users/dennis/dev/kg1/backend/node_modules/tap/node_modules/@tapjs/core/src/tap.ts:86
class TAP extends Test {
                  ^


ReferenceError: Cannot access 'Test' before initialization
    at <anonymous> (/Users/dennis/dev/kg1/backend/node_modules/tap/node_modules/@tapjs/core/src/tap.ts:86:19)
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at <anonymous> (/Users/dennis/dev/kg1/backend/node_modules/tap/node_modules/@tapjs/run/src/index.ts:19:7)

Node.js v20.9.0
```

**Comment by ydennisy** [comment]
Also blitzing `node_modules` and switching to node v16 has not helped.

**Comment by isaacs** [comment]
Ok! Why exactly do you have multiple copies of tapjs/core in there? Did you install tapjs/node-serialize explicitly? You don't need to do that. Remove that, delete package-lock.json and node_modules, and reinstall.

**Comment by ydennisy** [comment]
Wooooow!!!

Thanks all is fine now!

I remember I did that as when I installed an older version - I got an error with some message related to that package missing, installing it had fixed the issue at the time.

Thanks @isaacs !!
