### ISSUE TITLE
[BUG] Unexpected uncaught exception

### ISSUE THREAD

**Issue by ruyadorno** [tapjs/tapjs#961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the `CONTRIBUTING` guide on posting bugs, and `CODE_OF_CONDUCT`?

- [X] yes I read the things

### This issue exists in the latest tap version

- [X] I am using the latest tap

### Description

Ok, maybe this one is actually me failing to understand JavaScript but since this test was passing on pre-18-tap I feel like it should be good to bring this one up and well, maybe I'll understand one extra thing about how throwing exceptions works in js.

That said, the problem is that a thrown error becomes an unhandled rejection in case there's async code in between the place where it was generated and where the promise was awaited.

### Reproduction

Starting from:

```sh
$ npm init -y
$ npm i tap
```

Then add a test file, e.g:

<table><tbody>
  <tr><td><strong>test/index.js</strong></td></tr>
  <tr><td>
  
```js
const t = require('tap');

const sleep = (t) =>
  new Promise(res => { setTimeout(() => { res(null), t }) })

class Foo {
  async bar() {
    const p = this.baz()
    await sleep(10)
    await p;
  }
  async baz() {
    throw new Error('ERR');
  }
}

const f = new Foo();

t.rejects(
  f.bar(),
  /ERR/,
  'should reject on f.bar()'
);
```

</tr>
</tbody></table>

Running tests:

```sh
$ npx tap test/index.js
 SKIP  test/index.js 0 OK 662ms
 ~ no tests found

2> test/index.js
/Users/ruyadorno/tmp/test-tap18/test/index.js:13
    throw new Error('ERR');
          ^

Error: ERR
    at Foo.baz (/Users/ruyadorno/tmp/test-tap18/test/index.js:13:11)
    at Foo.bar (/Users/ruyadorno/tmp/test-tap18/test/index.js:8:20)
    at Object.<anonymous> (/Users/ruyadorno/tmp/test-tap18/test/index.js:20:5)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._compile (/Users/ruyadorno/tmp/test-tap18/node_modules/pirates/lib/index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at require.extensions.<computed> (/Users/ruyadorno/tmp/test-tap18/node_modules/@isaacs/ts-node-temp-fork-for-pr-2009/src/index.ts:1358:43)
    at Object.newLoader [as .js] (/Users/ruyadorno/tmp/test-tap18/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)

Node.js v20.8.1


  🌈 TEST COMPLETE 🌈


 FAIL  test/index.js 0 662ms

Asserts:  0 pass  1 fail  1 of 1 complete
Suites:   0 pass  1 fail  1 of 1 complete

# No coverage generated
# { total: 1, pass: 0, fail: 1 }
# time=746.023ms
```

If I take away L9 and thus I have no longer an `await` in between the LOC where the error is thrown and the LOC that awaits for that returning promise chain, tests passes since `t.reject` was able to properly handle the error:

```sh
$ npx tap test/index.js
 PASS  test/index.js 1 OK 667ms


  🌈 TEST COMPLETE 🌈


Asserts:  1 pass  0 fail  1 of 1 complete
Suites:   1 pass  0 fail  1 of 1 complete

# No coverage generated
# { total: 1, pass: 1 }
# time=739.433ms
```

### Environment

```
npm ls tap
test-tap18@1.0.0 /Users/ruyadorno/tmp/test-tap18
└── tap@18.5.2
```

```
npx tap versions
tap: 18.5.2
"@tapjs/config": 2.4.9
"@tapjs/core": 1.4.2
"@tapjs/run": 1.4.9
"@tapjs/stack": 1.2.6
"@tapjs/test": 1.3.13
tap-parser: 15.3.0
tap-yaml: 2.2.0
tcompare: 6.4.3
plugins:
  "@tapjs/after": 1.1.13
  "@tapjs/after-each": 1.1.13
  "@tapjs/asserts": 1.1.13
  "@tapjs/before": 1.1.13
  "@tapjs/before-each": 1.1.13
  "@tapjs/filter": 1.2.13
  "@tapjs/fixture": 1.2.13
  "@tapjs/intercept": 1.2.13
  "@tapjs/mock": 1.2.11
  "@tapjs/node-serialize": 1.2.2
  "@tapjs/snapshot": 1.2.13
  "@tapjs/spawn": 1.1.13
  "@tapjs/stdin": 1.1.13
  "@tapjs/typescript": 1.3.2
  "@tapjs/worker": 1.1.13
```

```
npx tap config list
# vim: set filetype=yaml :
color: true
coverage-report:
  - text
exclude:
  - "**/@(fixture*(s)|dist)/**"
include:
  - "**/@(test?(s)|__test?(s)__)/**/*.@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/*.@(test?(s)|spec).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
  - "**/test?(s).@(js|cjs|mjs|tap|cts|jsx|mts|ts|tsx)"
jobs: 8
reporter: base
snapshot-clean-cwd: true
timeout: 30
```

```
npx tap plugin list
@tapjs/after
@tapjs/after-each
@tapjs/asserts
@tapjs/before
@tapjs/before-each
@tapjs/filter
@tapjs/fixture
@tapjs/intercept
@tapjs/mock
@tapjs/node-serialize
@tapjs/snapshot
@tapjs/spawn
@tapjs/stdin
@tapjs/typescript
@tapjs/worker
```

**Comment by ruyadorno** [comment]
Also worth noting that if I change:

```patch
class Foo {
  async bar() {
    const p = this.baz()
-    await sleep(10)
+      .then(() => sleep(10))
    await p;
  }
  async baz() {
    throw new Error('ERR');
  }
}
```

Having the same async function but as part of the same thenable chain, the test also passes!

```sh
$ npx tap test/index.js
 PASS  test/index.js 1 OK 638ms


  🌈 TEST COMPLETE 🌈


Asserts:  1 pass  0 fail  1 of 1 complete
Suites:   1 pass  0 fail  1 of 1 complete

# No coverage generated
# { total: 1, pass: 1 }
# time=719.807ms
```

This leads me to think that there really might be a limitation with regards to introducing asynchronicity (via `await`) between an thrown error and its await expression but then I don't understand how the same test was passing in pre-18-tap 🤔 

- Maybe tap18 is just surfacing a legitimate problem? 
- Or is this valid JS syntax and this is a bug in tap18?

**Comment by isaacs** [comment]
What's happening here is that no handler is being added to the promise before the throw happens.

Simplified example, without tap, showing what's going on:

```js
const sleep = t => new Promise(res => setTimeout(() => res(), t))

const bar = async () => {
  const p = baz()
  p.__ID = 'BAZ RETURN'
  await sleep(10)
  await p
}

const baz = async () => {
  throw new Error('ERR')
}

const p = bar()
p.catch(er => console.error('caught', er))
process.on('unhandledRejection', (er, promise) => console.error({er, promise}))
```

While a throw in an async function will result in a rejected promise, an unhandled rejected promise in an async function will crash the process.

Tap 18 uses a somewhat more surgical approach for handling uncaught throws/rejections, so there's nothing attached until the main test starts. That's why it just crashes with node's less informative error rather than emitting a failing test, because the promise that is rejected unhandled is created _before_ the first output that the root tap test produces.

If you add `t.pass('this is fine')` before the `t.rejects`, then you'll see this:

```tap
TAP version 14                                                                     
ok 1 - this is fine                                                                
not ok 2 - ERR                                                                     
  ---                                                                              
  stack: |                                                                         
    baz (r.js:13:9)                                                                
    bar (r.js:6:13)                                                                
    r.js:17:11                                                                     
  at:                                                                              
    fileName: r.js                                                                 
    lineNumber: 13                                                                 
    columnNumber: 9                                                                
    functionName: baz                                                              
  tapCaught: unhandledRejection                                                    
  test: TAP                                                                        
  source: |                                                                        
                                                                                   
    const baz = async () => {                                                      
      throw new Error('ERR')                                                       
    --------^                                                                      
    }                                                                              
  ...                                                                              
                                                                                   
1..2                                                                               
# { total: 2, pass: 1, fail: 1 }
```

so it's more clear that it's an unhandledRejection that's causing the problem.

**Comment by ruyadorno** [comment]
Thank you so much @isaacs ❤️ so it turns out that tap18 is now surfacing a real problem and I should fix my code 😊
